# Site settings
title: My Little Website
url: "http://yourwebsite.com" #during jekyll serve, this will be your localhost
baseurl: #change this if your site is in a subfolder. Otherwise it will default to root

# Social
socialimg: /img/social.jpg

#Under the hood
include: ["_pages"]
permalink: /:title/
exclude: [.scss, README.md, gruntfile.js, package.json, .DS_Store, yarn.lock]
sass:
    load_paths:
        - node_modules
