# Site settings
title: Jekyll Starter Bulma #title of your site
url: "http://yourwebsite.com" #url for production. This is ignored during development but will be processed during build. During dev it will be 127.0.0.0:4000
baseurl: #change this if your site is not in root. (Example, your site is located under mysite.com/dev)

# Developer
developer: Company ABC
developerWebsite: "http://companyabc.com/"

# Social
socialimage: /img/social.jpg #default social image. Pages will use this if page specif socialimage is not specified

# Google Analytics
trackingID: UA-XXXXXXXXX-Y

# Pages and News
collections:
  pages:
    output: true
  news:
    output: true
    permalink: /news/:slug/


#Under the hood
exclude: [.scss, README.md, README.jpg gruntfile.js, package.json, .DS_Store, yarn.lock] #excludes these files from jekyll build
sass: #set directories to convert sass and scss files to css
    load_paths:
        - libraries
